service: idle-slayer-calculator-2
app: idle-slayer-calculator
provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    pythonBin: python3
    dockerizePip: non-linux
package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
functions:
  evolutionNames:
    handler: app.evolution_names
  giantNames:
    handler: app.giant_names
  upgradeNames:
    handler: app.upgrade_names
  armory:
    handler: app.armory
  stones:
    handler: app.stones
  randomBoxes:
    handler: app.random_boxes
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  calculateStats:
    handler: app.calculate_stats
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
